#!/bin/sh
bundle install
bundle exec jazzy \
  --clean \
  --umbrella-header BugfenderSDK.framework/Headers/BugfenderSDK.h \
  --framework-root ./BugfenderSDK.framework \
  --output ../BugfenderSDK-iOS-gh-pages \
  --sdk iphonesimulator
